/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.PersonProfile;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author pranavpatel
 */
public class ViewPersonJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private Person person;

    /**
     * Creates new form ViewPersonJPanel
     */
    public ViewPersonJPanel(JPanel userProcessContainer, PersonDirectory personDirectory, Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.person= person;
        refreshTextFields();
        ViewMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHCity = new javax.swing.JLabel();
        lblHState = new javax.swing.JLabel();
        lblHZip = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblHPhNum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtWSAdd = new javax.swing.JTextField();
        txtWUnitNum = new javax.swing.JTextField();
        txtWCity = new javax.swing.JTextField();
        txtWState = new javax.swing.JTextField();
        txtWZip = new javax.swing.JTextField();
        txtWPhNum = new javax.swing.JTextField();
        lblWSAdd = new javax.swing.JLabel();
        lblWUnitNum = new javax.swing.JLabel();
        txtHSAdd = new javax.swing.JTextField();
        txtHUnitNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHCity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtHState = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        txtHZip = new javax.swing.JTextField();
        txtLName = new javax.swing.JTextField();
        txtHPhNum = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblHA = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblHSAdd = new javax.swing.JLabel();
        lblWCity = new javax.swing.JLabel();
        lblWState = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lblWZip = new javax.swing.JLabel();
        lblHUnitNum = new javax.swing.JLabel();
        lblWPhNum = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        lblHCity.setText("City");

        lblHState.setText("State");

        lblHZip.setText("Zip Code");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add Person Profile ");

        lblHPhNum.setText("Phone Number");

        jLabel1.setText("First Name");

        txtWSAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWSAddActionPerformed(evt);
            }
        });

        lblWSAdd.setText("Street Address");

        lblWUnitNum.setText("Unit Number");

        txtHSAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHSAddActionPerformed(evt);
            }
        });

        jLabel2.setText("Last Name");

        jLabel3.setText("Social Security Number");

        jLabel4.setText("Age");

        lblHA.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblHA.setText("Home Address");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setText("Work Address");

        lblHSAdd.setText("Street Address");

        lblWCity.setText("City");

        lblWState.setText("State");

        lblWZip.setText("Zip Code");

        lblHUnitNum.setText("Unit Number");

        lblWPhNum.setText("Phone Number");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(btnSave)
                .addGap(42, 42, 42)
                .addComponent(btnUpdate)
                .addContainerGap(266, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(144, 144, 144)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblWZip)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblWSAdd)
                                                .addComponent(lblWCity)
                                                .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(59, 59, 59)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtWUnitNum, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblWState)
                                                .addComponent(lblWUnitNum)
                                                .addComponent(lblWPhNum)
                                                .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtWPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(txtWSAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jSeparator4)
                                        .addComponent(lblHZip)
                                        .addComponent(jSeparator3)
                                        .addComponent(jSeparator1)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtSSN)
                                                .addComponent(txtFName))
                                            .addGap(68, 68, 68)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtLName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                                    .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING))))
                                        .addComponent(lblHA)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblHSAdd)
                                                        .addComponent(lblHCity))
                                                    .addGap(163, 201, Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtHCity)
                                                    .addGap(59, 59, 59)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtHUnitNum)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblHState)
                                                        .addComponent(lblHUnitNum)
                                                        .addComponent(lblHPhNum))
                                                    .addGap(58, 58, 58))
                                                .addComponent(txtHState)
                                                .addComponent(txtHPhNum)))
                                        .addComponent(txtHSAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHZip, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)))
                                .addComponent(txtWZip, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(629, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblTitle)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblHA)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHSAdd)
                        .addComponent(lblHUnitNum))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHSAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHUnitNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblHState)
                        .addComponent(lblHCity))
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtHCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblHZip)
                        .addComponent(lblHPhNum))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtHZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblWSAdd)
                        .addComponent(lblWUnitNum))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtWSAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtWUnitNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblWState)
                        .addComponent(lblWCity))
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblWZip)
                        .addComponent(lblWPhNum))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtWPhNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtWZip, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(85, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtWSAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWSAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWSAddActionPerformed

    private void txtHSAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHSAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHSAddActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String fName = txtFName.getText();
        String lName = txtLName.getText();
        String sSN = txtSSN.getText();
        String age = txtAge.getText();
        String hSAdd = txtHSAdd.getText();
        String hUnitNum = txtHUnitNum.getText();
        String hCity = txtHCity.getText();
        String hState = txtHState.getText();
        String hZip = txtHZip.getText();
        String hPhNum = txtHPhNum.getText();
        String wSAdd = txtWSAdd.getText();
        String wUnitNum = txtWUnitNum.getText();
        String wCity = txtWCity.getText();
        String wState = txtWState.getText();
        String wZip = txtWZip.getText();
        String wPhNum = txtWPhNum.getText();
        
        if(fName.isBlank() || lName.isBlank() || sSN.isBlank() || age.isBlank() ||  wSAdd.isBlank() || wUnitNum.isBlank()|| wCity.isBlank() || wState.isBlank() || wZip.isBlank() || wPhNum.isBlank() || hSAdd.isBlank() || hUnitNum.isBlank()|| hCity.isBlank() || hState.isBlank() || hZip.isBlank() || hPhNum.isBlank()){
            JOptionPane.showMessageDialog(null,"All fields are mandatory.");
        }
        person.setFName(fName);
        person.setLName(lName);
        person.setSSN(sSN);
        person.setSSN(age);
        person.setWSAdd(wSAdd);
        person.setWUnitNum(wUnitNum);
        person.setWCity(wCity);
        person.setWState(wState);
        person.setWZip(wZip);
        person.setWPhNum(wPhNum);
        person.setHSAdd(hSAdd);
        person.setHUnitNum(hUnitNum);
        person.setHCity(hCity);
        person.setHState(hState);
        person.setHZip(hZip);
        person.setHPhNum(hPhNum);
        
   

        JOptionPane.showMessageDialog(null, "Successfully updated", "warning", JOptionPane.WARNING_MESSAGE);
        ViewMode();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        EditMode();
    }//GEN-LAST:event_btnUpdateActionPerformed
private void refreshTextFields(){
txtFName.setText(person.getFName());
txtLName.setText(person.getLName());
txtSSN.setText(person.getSSN());
txtAge.setText(person.getAge());
txtWSAdd.setText(person.getWSAdd());
txtWUnitNum.setText(person.getWUnitNum());

txtWState.setText(person.getWState());
txtWCity.setText(person.getWCity());
txtWZip.setText(person.getWZip());
txtWPhNum.setText(person.getWPhNum());
txtHSAdd.setText(person.getHSAdd());
txtHUnitNum.setText(person.getHUnitNum());

txtHState.setText(person.getHState());
txtHCity.setText(person.getHCity());
txtHZip.setText(person.getHZip());
txtHPhNum.setText(person.getHPhNum());



}
private void ViewMode(){
txtFName.setEnabled(false);
txtLName.setEnabled(false);
txtSSN.setEnabled(false);
txtAge.setEnabled(false);

txtWSAdd.setEnabled(false);
txtWUnitNum.setEnabled(false);
txtWCity.setEnabled(false);
txtWState.setEnabled(false);
txtWZip.setEnabled(false);
txtWPhNum.setEnabled(false);

txtHSAdd.setEnabled(false);
txtHState.setEnabled(false);
txtHUnitNum.setEnabled(false);
txtHCity.setEnabled(false);
txtHZip.setEnabled(false);
txtHPhNum.setEnabled(false);

btnSave.setEnabled(false);
btnUpdate.setEnabled(true);
}
private void EditMode(){
    txtFName.setEnabled(true);
txtLName.setEnabled(true);
txtSSN.setEnabled(true);
txtAge.setEnabled(true);

txtWSAdd.setEnabled(true);
txtWUnitNum.setEnabled(true);
txtWCity.setEnabled(true);
txtWState.setEnabled(true);
txtWZip.setEnabled(true);
txtWPhNum.setEnabled(true);

txtHSAdd.setEnabled(true);
txtHState.setEnabled(true);
txtHUnitNum.setEnabled(true);
txtHCity.setEnabled(true);
txtHZip.setEnabled(true);
txtHPhNum.setEnabled(true);
    btnSave.setEnabled(true);
    btnUpdate.setEnabled(false);

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblHA;
    private javax.swing.JLabel lblHCity;
    private javax.swing.JLabel lblHPhNum;
    private javax.swing.JLabel lblHSAdd;
    private javax.swing.JLabel lblHState;
    private javax.swing.JLabel lblHUnitNum;
    private javax.swing.JLabel lblHZip;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWCity;
    private javax.swing.JLabel lblWPhNum;
    private javax.swing.JLabel lblWSAdd;
    private javax.swing.JLabel lblWState;
    private javax.swing.JLabel lblWUnitNum;
    private javax.swing.JLabel lblWZip;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtHCity;
    private javax.swing.JTextField txtHPhNum;
    private javax.swing.JTextField txtHSAdd;
    private javax.swing.JTextField txtHState;
    private javax.swing.JTextField txtHUnitNum;
    private javax.swing.JTextField txtHZip;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWCity;
    private javax.swing.JTextField txtWPhNum;
    private javax.swing.JTextField txtWSAdd;
    private javax.swing.JTextField txtWState;
    private javax.swing.JTextField txtWUnitNum;
    private javax.swing.JTextField txtWZip;
    // End of variables declaration//GEN-END:variables
}
