/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import java.awt.CardLayout;
import model.Person;
import model.PersonDirectory;
import ui.PersonProfile.PersonProfileJPanel;
/**
 *
 * @author pranavpatel
 */
public class MainJFrame extends javax.swing.JFrame {
private PersonDirectory personDirectory;
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.personDirectory= new PersonDirectory();
        generateDemoData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        btnPersonProfile = new javax.swing.JButton();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnPersonProfile.setText("Persons Profiles");
        btnPersonProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPersonProfile)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnPersonProfile)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(topJPanel);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPersonProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonProfileActionPerformed
        // TODO add your handling code here:
        PersonProfileJPanel panel = new PersonProfileJPanel (userProcessContainer,personDirectory);
        userProcessContainer.add("PersonProfileJPanel",panel);

        CardLayout layout =(CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPersonProfileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    private void generateDemoData(){
    Person newPerson=personDirectory.addPerson();
    newPerson.setFName("Pranav");
    newPerson.setLName("Patel");
    newPerson.setSSN("123456789");
    newPerson.setAge("22");
    newPerson.setHSAdd("16 lakeville");
    newPerson.setHUnitNum("11");
    newPerson.setHState("MA");
    newPerson.setHCity("Boston");
    newPerson.setHZip("02130");
    newPerson.setHPhNum("857929223");
    newPerson.setWSAdd("16 lakeville");
    newPerson.setWUnitNum("11");
    newPerson.setWState("MA");
    newPerson.setWCity("Boston");
    newPerson.setWZip("02130");
    newPerson.setWPhNum("857929223");
   
    
    
    
    Person anotherNewPerson = personDirectory.addPerson();
    anotherNewPerson.setFName("Nancy");
    anotherNewPerson.setLName("Taswala");
    anotherNewPerson.setSSN("123456700");
    anotherNewPerson.setAge("19");
    anotherNewPerson.setHSAdd("Boylston Steet");
    anotherNewPerson.setHUnitNum("10");
    anotherNewPerson.setHState("MA");
    anotherNewPerson.setHCity("Boston");
    anotherNewPerson.setHZip("02115");
    anotherNewPerson.setHPhNum("857929225");
    anotherNewPerson.setWSAdd("Boylston Steet");
    anotherNewPerson.setWUnitNum("10");
    anotherNewPerson.setWState("MA");
    anotherNewPerson.setWCity("Boston");
    anotherNewPerson.setWZip("02115");
    anotherNewPerson.setWPhNum("857929225");
    
    Person thirdPerson = personDirectory.addPerson();
thirdPerson.setFName("Riddhi");
thirdPerson.setLName("Patel");
thirdPerson.setSSN("123456701");
thirdPerson.setAge("30");
thirdPerson.setHSAdd("12 Greenway Lane");
thirdPerson.setHUnitNum("5");
thirdPerson.setHState("MA");
thirdPerson.setHCity("Cambridge");
thirdPerson.setHZip("02138");
thirdPerson.setHPhNum("857929227");
thirdPerson.setWSAdd("12 Greenway Lane");
thirdPerson.setWUnitNum("5");
thirdPerson.setWState("MA");
thirdPerson.setWCity("Cambridge");
thirdPerson.setWZip("02138");
thirdPerson.setWPhNum("857929227");

Person fourthPerson = personDirectory.addPerson();
fourthPerson.setFName("Krunal");
fourthPerson.setLName("Vagashiya");
fourthPerson.setSSN("123456702");
fourthPerson.setAge("25");
fourthPerson.setHSAdd("123 Commonwealth Ave");
fourthPerson.setHUnitNum("8");
fourthPerson.setHState("MA");
fourthPerson.setHCity("Boston");
fourthPerson.setHZip("02116");
fourthPerson.setHPhNum("857929228");
fourthPerson.setWSAdd("123 Commonwealth Ave");
fourthPerson.setWUnitNum("8");
fourthPerson.setWState("MA");
fourthPerson.setWCity("Boston");
fourthPerson.setWZip("02116");
fourthPerson.setWPhNum("857929228");

Person fifthPerson = personDirectory.addPerson();
fifthPerson.setFName("Virat");
fifthPerson.setLName("Kohli");
fifthPerson.setSSN("123456703");
fifthPerson.setAge("28");
fifthPerson.setHSAdd("45 Charles Street");
fifthPerson.setHUnitNum("3");
fifthPerson.setHState("MA");
fifthPerson.setHCity("Boston");
fifthPerson.setHZip("02114");
fifthPerson.setHPhNum("857929229");
fifthPerson.setWSAdd("45 Charles Street");
fifthPerson.setWUnitNum("3");
fifthPerson.setWState("MA");
fifthPerson.setWCity("Boston");
fifthPerson.setWZip("02114");
fifthPerson.setWPhNum("857929229");
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPersonProfile;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel topJPanel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
